apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: PatrikHarmanos/ambulance-wl-webapi
    newName: PatrikHarmanos/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
    newTag: main # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}

  - name: patrikharmanos/wac
    newName: patrikharmanos/wac # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
    newTag: main # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}

  - name: milung/ufe-controller
    newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
    newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
